export const MEDICATION_LIST_FETCHED = 'MEDICATION_LIST_FETCHED';
export const SET_ERROR_MEDICATION_LIST = 'SET_ERROR_MEDICATION_LIST';
export const MEDICATION_INFO_FETCHED = 'MEDICATION_INFO_FETCHED';
export const MEDICATION_INFO_FETCHED_ERROR = 'MEDICATION_INFO_FETCHED_ERROR';
