export const PATIENT_INFO_FETCHED_ERROR = 'PATIENT_INFO_FETCHED_ERROR';
export const PATIENT_INFO_FETCHED = 'PATIENT_INFO_FETCHED';
export const PATIENT_LIST_FETCHED = 'PATIENT_LIST_FETCHED';
export const VIEWING_PATIENT_INFO_FETCHED = 'VIEWING_PATIENT_INFO_FETCHED';
