export const USERS_LIST_FETCHED = 'USERS_LIST_FETCHED';
export const SET_ERROR_USER_LIST = 'SET_ERROR_USER_LIST';
export const USER_INFO_FETCHED = 'USER_INFO_FETCHED';
export const USER_INFO_FETCHED_ERROR = 'USER_INFO_FETCHED_ERROR';
